name = "make_vegetable_driver"
version = "1.0.0"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "2021 Brad Richardson"

[dependencies]
  iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string.git", tag = "v2.0.0" }
  parff = { git = "https://gitlab.com/everythingfunctional/parff.git", tag = "v2.0.0" }
